In [1]:
import cv2

In [2]:
import numpy 

In [3]:
image = numpy.ones((600,600,3))

In [4]:
center_coordinates=(300,300)
radius=190
color = (255, 128, 0)
thickness=20


image = cv2.circle(image, center_coordinates, radius, color, thickness)

In [5]:

color = (255, 128, 0)
thickness = 20
image = cv2.line(image, (110,300), (490,300) , color, thickness)

In [6]:
start_point = (185, 150)
end_point = (420, 440)
color = (255, 128, 0)
thickness = 20
image = cv2.line(image,start_point, end_point  , color, thickness)

In [7]:
start_point = (420, 160)
end_point = (180, 440)
color = (255, 128, 0)
thickness = 20
image = cv2.line(image,start_point, end_point  , color, thickness)

In [8]:
start_point = (140, 210)
end_point = (300, 480)
color = (255, 128, 0)
thickness = 30
image = cv2.line(image,start_point, end_point  , color, thickness)

In [9]:
start_point = (140, 210)
end_point = (460, 210)
color = (255, 128, 0)
thickness = 30
image = cv2.line(image,start_point, end_point  , color, thickness)

In [10]:
start_point = (300, 480)
end_point = (460, 210)
color = (255, 128, 0)
thickness = 30
image = cv2.line(image,start_point, end_point  , color, thickness)

In [11]:
start_point = (140, 210)
end_point = (300, 480)
color = (0, 0, 0)
thickness = 20
image = cv2.line(image,start_point, end_point  , color, thickness)

In [12]:
start_point = (140, 210)
end_point = (460, 210)
color = (0, 0, 0)
thickness = 20
image = cv2.line(image,start_point, end_point  , color, thickness)

In [13]:
start_point = (300, 480)
end_point = (460, 210)
color = (0, 0, 0)
thickness = 20
image = cv2.line(image,start_point, end_point  , color, thickness)

In [14]:
color = (0, 0, 0)
thickness = 10
image = cv2.line(image, (115,300), (485,300) , color, thickness)

In [15]:
start_point = (185, 150)
end_point = (420, 440)
color = (0, 0, 0)
thickness = 10
image = cv2.line(image,start_point, end_point  , color, thickness)

In [16]:
start_point = (420, 160)
end_point = (180, 440)
color = (0, 0, 0)
thickness = 10
image = cv2.line(image,start_point, end_point  , color, thickness)

In [17]:
center_coordinates=(300,300)
radius=200
color = (0, 0, 0)
thickness=25


image = cv2.circle(image, center_coordinates, radius, color, thickness)

In [18]:


pt1 = (151, 216)
pt2 = (300, 469)
pt3 = (449, 216)
triangle_cnt = numpy.array( [pt1, pt2, pt3] )

cv2.drawContours(image, [triangle_cnt], 0, (255, 128, 0), -1)


array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
pt1 = (160, 221)
pt2 = (300, 459)
pt3 = (440, 221)
triangle_cnt = numpy.array( [pt1, pt2, pt3] )

cv2.drawContours(image, [triangle_cnt], 0, (255, 255, 255), -1)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
start_point = (160, 221)
end_point = (300, 300)
color = (255, 128, 0)
thickness = 10
image = cv2.line(image,start_point, end_point  , color, thickness)

In [21]:
start_point = (300, 459)
end_point = (300, 300)
color = (255, 128, 0)
thickness = 10
image = cv2.line(image,start_point, end_point  , color, thickness)

In [22]:
start_point = (440,221)
end_point = (300, 300)
color = (255, 128, 0)
thickness = 10
image = cv2.line(image,start_point, end_point  , color, thickness)

In [23]:
pt1 = (201, 243)
pt2 = (300, 410)
pt3 = (400, 243)
triangle_cnt = numpy.array( [pt1, pt2, pt3] )

cv2.drawContours(image, [triangle_cnt], 0, (255, 128, 0), -1)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
start_point = (151, 216)
end_point = (300, 300)
color = (0, 0, 0)
thickness = 5
image = cv2.line(image,start_point, end_point  , color, thickness)

In [25]:
start_point = (300, 470)
end_point = (300, 300)
color = (0, 0, 0)
thickness = 5
image = cv2.line(image,start_point, end_point  , color, thickness)

In [26]:
start_point = (449,216)
end_point = (300, 300)
color = (0, 0, 0)
thickness = 5
image = cv2.line(image,start_point, end_point  , color, thickness)

In [27]:
pt1 = (225, 258)
pt2 = (300, 385)
pt3 = (375, 258)
triangle_cnt = numpy.array( [pt1, pt2, pt3] )

cv2.drawContours(image, [triangle_cnt], 0, (255, 128, 0), -1)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
start_point = (221, 255)
end_point = (380, 255)
color = (0, 0, 0)
thickness = 13
image = cv2.line(image,start_point, end_point  , color, thickness)

In [29]:
start_point = (221, 255)
end_point = (300, 390)
color = (0, 0, 0)
thickness = 13
image = cv2.line(image,start_point, end_point  , color, thickness)

In [30]:
start_point = (300,390)
end_point = (380, 255)
color = (0, 0, 0)
thickness = 13
image = cv2.line(image,start_point, end_point  , color, thickness)

In [31]:
pt1 = (245, 268)
pt2 = (300, 365)
pt3 = (355, 268)
triangle_cnt = numpy.array( [pt1, pt2, pt3] )

cv2.drawContours(image, [triangle_cnt], 0, (255, 255,255), -1)

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
cv2.imshow('myjpg',image)
cv2.waitKey()
cv2.destroyAllWindows()